### ISSUE TITLE
Identity on Moonbeam address not showing in explorer

### ISSUE THREAD

**Issue by CertHum-Jim** [subscan-explorer/subscan-issue-tracker#100]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Moonbeam

### Steps to reproduce

Visit: https://moonbeam.subscan.io/validator_list?status=validator&page=3 and there's no identity next to 0x3431e0de19a9eb54d71be71a2fddb7e7b3225643.
Visit https://moonbeam.subscan.io/account/0x3431e0de19a9eb54d71be71a2fddb7e7b3225643 and it says account is unknown (all though there is identity info below the account. This previously showed accurately like other addresses with a Reasonable jusgement.

Here's the on-chain infor for the address.

[
  {
    judgements: [
      [
        1
        Reasonable
      ]
    ]
    deposit: 12,580,000,000,000,000,000
    info: {
      additional: []
      display: {
        Raw: CertHum
      }
      legal: {
        Raw: CertHum
      }
      web: {
        Raw: https://www.certhum.com/staking
      }
      riot: None
      email: {
        Raw: contact@certhum.com
      }
      pgpFingerprint: null
      image: None
      twitter: {
        Raw: @CertHum
      }
    }
  }
  null
]

### Expected output

Identity should be shown with the account.

### Actual output

Account showing as 'Unknown'

**Comment by freehere107** [comment]
@CertHum-Jim This issue has been fixed.
