### ISSUE TITLE
Delegation Amount shown incorrectly

### ISSUE THREAD

**Issue by DrW3RK** [subscan-explorer/subscan-issue-tracker#102]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot

### Steps to reproduce

I've updated my delegation amount from 3500 DOT to 4400 DOT and added delegation on a whitelisted caller. It is interesting to see that only whitelisted caller shows the updated delegation amount and the tracks delegated to previously have no change. https://polkadot.subscan.io/delegated_v2?address=14aZsGMA4aPrSuV4MSSpumtYwxuNNrDc3vHu12K85xYh9qcB

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/83621a95-6ac7-4256-9e28-6bf8a80a2a78">

### Expected output

All tracks should show 4400 DOT delegated

### Actual output

Only one track shows 4400 DOT delegated and the other tracks still show the previous delegation amount

**Comment by cuckooemm** [comment]
We have fixed this issue, thanks for your feedback
