### ISSUE TITLE
Unable to find endpoints for XCM transfers

### ISSUE THREAD

**Issue by dudo50** [subscan-explorer/subscan-issue-tracker#107]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Both

### Steps to reproduce

Hello, we would like to use subscan API for our tool called [XCM Visualizator](https://xcm-visualizator.tech/)

However, we cannot find endpoints that would retrieve XCM messages from the docs provided. 

Could you please point us to snippets?
If there is no way to query XCM messages now, will there be anytime soon?

Thanks!

### Expected output

Endpoints

### Actual output

Not found

**Comment by freehere107** [comment]
@dudo50 XCM API not release yet.  There is still a possibility of break change

**Comment by dudo50** [comment]
@freehere107  Any estimated time of release?

**Comment by freehere107** [comment]
@dudo50 Xcm endpoint has been released https://support.subscan.io/folder-2399846
