### ISSUE TITLE
(PEAQ) Discrepancy in Circulating Supply Data between Tokenomics and Subscan

### ISSUE THREAD

**Issue by Aiichiro712** [subscan-explorer/subscan-issue-tracker#111]
**Issue Summary**:
The project's Tokenomics page currently lists a circulating supply of 377,650,940 tokens. However, Subscan is showing a circulating supply of 1.196B tokens, with an increase of 150 million in the past 24 hours.

**Steps to Reproduce**:
1. Visit the [Tokenomics page](https://docs.peaq.network/docs/learn/tokenomics/).
2. Visit Subscan (https://peaq.subscan.io/) to view the current circulating supply.

**Expected Result:**
The circulating supply figures should match or have a confirmed explanation for any discrepancy.

**Actual Result**:
There is a large difference between the two numbers, raising concerns about data accuracy for the community.

**Request**:
Could we please get:
- A correction of this discrepancy if it's an error.
- Or, a confirmation if the numbers on Subscan are accurate, along with an explanation.

This would help ensure transparency and accuracy for all community members. Thank you for looking into this!

**Comment by freehere107** [comment]
Hi, @Aiichiro712 I will check it

**Comment by freehere107** [comment]
@makariosousta We are working with the peaq team to resolve this issue.

**Comment by makariosousta** [comment]
> @makariosousta We are working with the peaq team to resolve this issue.

okay is it a difficult bug that needs a lot time to be fixed?

**Comment by freehere107** [comment]
This issue has been resolved

**Comment by makariosousta** [comment]
Thank you!

**Comment by Aiichiro712** [comment]
Thanks a lot
