### ISSUE TITLE
PEAQ Supply bug

### ISSUE THREAD

**Issue by makariosousta** [subscan-explorer/subscan-issue-tracker#112]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

PEAQ

### Steps to reproduce

Just check the supply it is wrong and it have been days please fix

### Expected output

Correct the supply

### Actual output

Correct the supply

**Comment by makariosousta** [comment]
![chain_mc](https://github.com/user-attachments/assets/f42a8383-2744-40f7-9948-249426056c14)
![cryptorank_mc](https://github.com/user-attachments/assets/2ee44ffd-495b-4d99-9912-d51e1282ba81)
those are the correct stats, still waiting what happened?

**Comment by freehere107** [comment]
This issue has been resolved

**Comment by makariosousta** [comment]
Thank you!
