### ISSUE TITLE
PEAQ subscan has wrong supply (bug that is showing staked tokens)

### ISSUE THREAD

**Issue by makariosousta** [subscan-explorer/subscan-issue-tracker#113]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

PEAQ

### Steps to reproduce

Visit https://peaq.subscan.io/ and you will see that it shows Circulating 1.561B (37.16%) which is wrong. There is a bug that is showing the staked tokens. When are you going to fix it finally?

### Expected output

377,650,140 is the correct value as described on Chain Broker and CryptoRank as you can see in the following screenshots
![chain_mc](https://github.com/user-attachments/assets/f2f91999-9d34-4e14-9f8e-b587f3fe1ff0)
![cryptorank_mc](https://github.com/user-attachments/assets/e62573a7-33ad-45e9-bd15-bb5c5b18de33)

### Actual output

Circulating 1.561B (37.16%) is wrong as supply please fix it finally

### Additional factoids or references

Could you please tell me when are you going to fix it? It is destroying the general picture of the project...

**Comment by freehere107** [comment]
This issue has been resolved

**Comment by makariosousta** [comment]
Thank you!
