### ISSUE TITLE
Account Balance History is not updating

### ISSUE THREAD

**Issue by LaplaceTransformS** [subscan-explorer/subscan-issue-tracker#116]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot

### Steps to reproduce

Via browser, select any account and navigate to the balance history tab then download page data.  The balance is static since era 1636.  Via api, query endpoint https://polkadot.api.subscan.io/api/scan/account/balance_history and the result doesn't include later eras terminating with 'status': 'incomplete'

### Expected output

11/23/2024	1563.537103
11/24/2024	1564.050847
11/25/2024	new balance
11/26/2024	new balance
11/27/2024	new balance
11/28/2024	new balance
11/29/2024	new balance

### Actual output

11/23/2024	1563.537103
11/24/2024	1564.050847
11/25/2024	1564.050847
11/26/2024	1564.050847
11/27/2024	1564.050847
11/28/2024	1564.050847
11/29/2024	1564.050847

**Comment by cuckooemm** [comment]
This issue has been fixed. Thanks for the feedback.
