### ISSUE TITLE
Missing staking_info from API scan/staking/nominator with controller set via proxy

### ISSUE THREAD

**Issue by playing-with-dust** [subscan-explorer/subscan-issue-tracker#17]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Kusama

### Steps to reproduce

Running /staking/nominator with this address (which is set up as a nominator)

`curl -X POST 'https://polkadot.api.subscan.io/api/scan/staking/nominator' \
  --header 'Content-Type: application/json' \
  --header 'X-API-Key: YOUR_KEY' \
  --data-raw '{
    "address": "Ehf8o6btGt6uuJfUPrDZ91HMhq5N7nCT9uumxqCwy1y5Doc"
  }'
`

### Expected output

staking_info which contains the controller:

https://kusama.subscan.io/account/FLzgz4qt5foC1DXRHQQwC2cLwu39eGkhx93x7UsM5uniBvM 

### Actual output

I get a staking_info of null.

### Additional factoids or references

This is due, I think, to the controller being set within this proxied batch call (rather than from the stash itself):

https://kusama.subscan.io/extrinsic/0x2fe3b90d18f8408a139ebc819b4e6b956c0f6c07fb4ecbe9037b93d03ed953be

**Comment by freehere107** [comment]
@playing-with-dust  Thank you feedback, we will check it

**Comment by freehere107** [comment]
@playing-with-dust This issue has been fixed, thank you feedback

**Comment by playing-with-dust** [comment]
Can confirm this is fixed - thank you!
