### ISSUE TITLE
Reward&Slash "download all data" URL in lagging more than 5 days behind 

### ISSUE THREAD

**Issue by p4tpr0** [subscan-explorer/subscan-issue-tracker#18]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

polkadot

### Steps to reproduce

Open Reward&Slash for your account to display full Reward&Slash history
Scroll down and click "Download all data", validate captcha, download file
Get URL origin of file
Use that URL to grab updated file few days later

### Expected output

The file should enclose current/up to date data.

### Actual output

The file lags behind by few days: file downloaded directly via URL the 19th shows latest data from the 13th. Few days ago, the file latest data was from the 12th.
The file seems updated somehow, but never current.

### Additional factoids or references

Downloading the file through the initial process (click-click/captcha/etc.) yields to an up to date file.

**Comment by freehere107** [comment]
hello, @p4tpr0  You should not use the past download url directly, this data will not change. You need to update the subscan via the download button to get the new download link (even if the download link is the same as the previous one)

**Comment by p4tpr0** [comment]
Hello @freehere107 , what would be the correct way to periodically grab my staking history (in order to inject data into my processing software) ?

**Comment by freehere107** [comment]
@p4tpr0 You can use this API https://docs.api.subscan.io/#reward-slash

**Comment by p4tpr0** [comment]
Thanks. 
I've asked for an access to the API few days ago, any idea of the usual delivery time?

**Comment by freehere107** [comment]
@p4tpr0 What is your email address when you applied API KEY?

**Comment by p4tpr0** [comment]
I've used a unique email address crafted only for that application. Publicly I can only tell it's from a subdomain of patpro.net, that should make it quite simple to find on your side hopefully.

**Comment by p4tpr0** [comment]
Ok, just received my API key! Thanks.

**Comment by p4tpr0** [comment]
I might have closed the issue too soon. I've tried to get the info I need via the API, it seems impossible and the documentation does not show a singie example / command that would allow me to do so. 
How would you get the same info as the link https://polkadot.subscan.io/reward?address=15xkJyVN5H...&role=nominator ?
I need at least Event Index,Era,Date,Value,Action…

**Comment by freehere107** [comment]
@p4tpr0 use this api https://docs.api.subscan.io/#reward-slash-v2

**Comment by p4tpr0** [comment]
Thanks! I've been able to get data I need from apiv2. Now I can close the issue. Thanks again for your work.
