### ISSUE TITLE
Crowdloan contribution for no balance account

### ISSUE THREAD

**Issue by DavyChang** [subscan-explorer/subscan-issue-tracker#21]
### Network(s)

Polkadot, Kusama

### Description

A crowdloan contributor who has no KSM/DOT balance can't see his account detail page, which means he can't see his contribution amount.
 

### Use cases

If a user contributes all his KSM/DOT in crowdloan, he will have no way to find his contribution amount.

**Comment by MittWillson** [comment]
Can you provide a relevant account so we can see how to optimize this

**Comment by DavyChang** [comment]
D6PAkwbWsLzVm1GF16Phh3mqoymE374ia21tfa6XjsKYtzv
This is a Kusama account, has no KSM. and it contributed in Khala‘s account
