### ISSUE TITLE
I unlocked astr but the transaction was successful but why is astr still locked in the dapp

### ISSUE THREAD

**Issue by Kangbin111** [subscan-explorer/subscan-issue-tracker#22]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Astra

### Steps to reproduce

3

### Expected output

I unlocked astr but the transaction was successful but why is astr still locked in the dapp

### Actual output

I unlocked astr but the transaction was successful but why is astr still locked in the dapp

**Comment by fiexer** [comment]
@Kangbin111 please share your TX so I can check this issue.
If you unstaked your ASTR tokens from dApp staking, there is still a 10-day unbond period that you need to go through. More info can be found here: https://docs.astar.network/dapp-staking/for-stakers/unbond-your-stake
