### ISSUE TITLE
Azero Account balance shows "Others" category with 199.9% of total

### ISSUE THREAD

**Issue by oliverkx** [subscan-explorer/subscan-issue-tracker#24]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Aleph Zero Mainnet

### Steps to reproduce

1 - I have a pair of Mainnet Aleph Zero account used for staking: a controller account and a Stash account. The stash account is 99.9% staked.
2 - in Chrome and Firefox on Windows 10, I navigate to alephzero.subscan.io and search for my account address to see the balances.

### Expected output

I would expect to see the balances displayed as "Transferable (0.0%)" and "Staked (99.9%)".

### Actual output

In addition to "Transferable (0.0%)" and "Staked (99.9%)", I also see "Others (199.9%)".

### Additional factoids or references

I have no idea what "Others" means. The balance listed under this category does not match the amount I have transferred to the account. I also haven't been able to find any information or details about this category. Besides, the categories now add up to close to 300%, which seems odd
![Subscan](https://user-images.githubusercontent.com/12791021/172035973-a899a295-6418-4e6e-9654-8eabc30a62f5.png)
.

**Comment by MittWillson** [comment]
The Others is total of locking balances, includes right side panel values, but I see the right panel has empty values, It is a bug we will fix it.

**Comment by carlhong** [comment]
It is fixed now.
