### ISSUE TITLE
Validator Reward Discrepancy with Other Explorers

### ISSUE THREAD

**Issue by m-saxemberg** [subscan-explorer/subscan-issue-tracker#41]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot

### Steps to reproduce

There is a discrepancy between other explorers and Subscan when it comes to Validator rewards
Era 961 is missing here
https://polkadot.subscan.io/account/153YD8ZHD9dRh82U419bSCB5SzWhbdAFzjj4NtA5pMazR2yC?tab=reward
whereas other explorers have it 
https://polkadot.polkastats.io/account/153YD8ZHD9dRh82U419bSCB5SzWhbdAFzjj4NtA5pMazR2yC
https://polkaholic.io/account/5G7F4oJDMNMxFb1x6N6bJ3LvbNX3uKc7vEzaDbAjGGZUEXFV?group=rewards&chainfilters=all

The missing extrinsic 
https://polkadot.subscan.io/extrinsic/13871910-3

### Expected output

13886301-42 | Staking (Rewarded) | 153YD8....azR2yC | 962 | 29.033804DOT | 1 day 11 hrs ago
13871910-3 | Staking (Rewarded) | 153YD8....azR2yC | 961 | 21.563889 DOT  | 2 days 11 hrs ago
13857521-41 | Staking (Rewarded) | 153YD8....azR2yC | 960 | 22.74722911DOT | 3 days 11 hrs ago

	

### Actual output

13886301-42 | Staking (Rewarded) | 153YD8....azR2yC | 962 | 29.033804DOT | 1 day 11 hrs ago
-- | -- | -- | -- | -- | --
13857521-41 | Staking (Rewarded) | 153YD8....azR2yC | 960 | 22.74722911DOT | 3 days 11 hrs ago

**Comment by m-saxemberg** [comment]
Just a little update on this issue. Era 969 is missing now:

Expected Output

13987040-3 | Staking (Rewarded) | 153YD8....azR2yC | 969 | 46.145027 DOT  | 3 hrs ago

13972643-43 | Staking (Rewarded) | 153YD8....azR2yC | 968 | 30.87260868DOT | 1 day 3 hrs ago

Actual Output
13972643-43 | Staking (Rewarded) | 153YD8....azR2yC | 968 | 30.87260868DOT | 1 day 3 hrs ago

Links to explorers
https://polkadot.subscan.io/account/153YD8ZHD9dRh82U419bSCB5SzWhbdAFzjj4NtA5pMazR2yC?tab=reward
https://polkadot.polkastats.io/account/153YD8ZHD9dRh82U419bSCB5SzWhbdAFzjj4NtA5pMazR2yC

**Comment by freehere107** [comment]
@m-saxemberg We have made a repair recently, if you encounter the problem again, please let me know in time
