### ISSUE TITLE
CLV price feed is wrong (token mismatch)

### ISSUE THREAD

**Issue by iamexe** [subscan-explorer/subscan-issue-tracker#43]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Clover

### Steps to reproduce

1. https://www.coingecko.com/en/coins/clover-finance is correct
2. https://www.coingecko.com/en/coins/clover is wrong
3. The price feed is being taken from 'clover' and not from 'clover-finance'

### Expected output

Token amount multiplied by the price value here: https://www.coingecko.com/en/coins/clover-finance

### Actual output

Token amount multiplied by the price value here: https://www.coingecko.com/en/coins/clover

**Comment by freehere107** [comment]
@iamexe This issue has been fixed. Thank you feedback
