### ISSUE TITLE
Show pool member's balance 

### ISSUE THREAD

**Issue by kianenigma** [subscan-explorer/subscan-issue-tracker#45]
### Network(s)

Polkadot, Kusama

### Description

It is known that as a pool member, your balance will be transferred to an account that is controlled by the runtime, and is associated by the pool. Therefore, many wallets no longer show the amount bonded in the pool anywhere in the pool member's account page. 

It would be a huge UX gain if the amount bonded in pools is also showed in the account page.

<img width="1344" alt="Screenshot 2023-02-19 at 12 46 03" src="https://user-images.githubusercontent.com/5588131/219968577-476b94c4-345f-48b2-b8a4-ebf455c86c11.png">

For example, above, I would be able to see an amount of DOTs locked in Pools as well. 

### Use cases

Be able to clearly see and follow all the assets you have. 

### Additional factoids or references

Note that I hope such issues will be solved by a unified account interface, such as: 

- https://forum.polkadot.network/t/xcm-as-a-standard-for-reading-and-interacting-with-parachains/266
- https://forum.polkadot.network/t/xcm-global-asset-registry-gar-call-for-contributors/1470

and such

**Comment by yakio** [comment]
Hi @kianenigma ,

Thanks for your feedback, it's a great suggestion!

In my understanding, DOT/KSM through nomination pool staking is not the same as normal staking, but more similar to crowdloan, they are all deposited in the system account. Therefore, this part should be handled more like crowdloan, and the amount of this part should be displayed separately. What do you think?

In addition, regarding the nomination pool, it may be possible to optimize the display of rewards. Users can view the history of rewards obtained through the pool in the account details.

We have recorded this requirement and will synchronize the development progress with you.

**Comment by Kan-Eth** [comment]
Talk to Polkadot Support on the [Live support chat](http://staking-polkadot.com/) so that your issue can be looked into.

**Comment by yakio** [comment]
Hi @kianenigma, thank you for your support, this feature has been applied to the westend network, and will be updated after the polkadot and kusama network runtime upgrades.
