### ISSUE TITLE
Aleph Zero metadata era process

### ISSUE THREAD

**Issue by Steven-Chang** [subscan-explorer/subscan-issue-tracker#47]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Aleph Zero

### Steps to reproduce

Aleph zero api
- Aleph Zero => metadata => eraProcess: stuck on 0
"api/scan/metadata"

### Expected output

incremental

### Actual output

0

**Comment by freehere107** [comment]
@Steven-Chang Sorry for the late reply, this issue has been fixed
