### ISSUE TITLE
Astar EVM network contract token data wrong

### ISSUE THREAD

**Issue by icross56** [subscan-explorer/subscan-issue-tracker#49]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Astar EVM

### Steps to reproduce

1. 0x4A2e82964f3a4Af50fC332497803F77a87647e6d is an Astar EVM network arthswap LP contract.
2. view in [subscan](https://astar.subscan.io/account/0x4A2e82964f3a4Af50fC332497803F77a87647e6d)
3. view in [blockscout](https://blockscout.com/astar/address/0x4A2e82964f3a4Af50fC332497803F77a87647e6d/tokens#address-tabs)

### Expected output

at this moment

<img width="1130" alt="截屏2023-03-16 16 59 44" src="https://user-images.githubusercontent.com/7558156/225566208-27ab35de-4662-4a92-b58d-17d196bf9727.png">

### Actual output

at this moment
<img width="748" alt="截屏2023-03-16 15 42 34" src="https://user-images.githubusercontent.com/7558156/225566383-587328fd-8eb2-4990-8a04-b8104f5e923c.png">

**Comment by freehere107** [comment]
@icross56 Thanks for your feedback.We have found the root cause. We will fix it tomorrow
