### ISSUE TITLE
API output do not match to subscan.io output (missing transactions)

### ISSUE THREAD

**Issue by botnumberseven** [subscan-explorer/subscan-issue-tracker#55]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

OriginTrail Parachain

### Steps to reproduce

Running evm/transactions API for some blocks I see output different to the one I can see at subscan.io
For example:
  curl -X POST 'https://origintrail.api.subscan.io/api/scan/evm/transactions' \
  --header 'Content-Type: application/json' \
  --header 'X-API-Key: YOU_API_KEY' \
  --data-raw '{
    "block_num": 1471595
  }'

I do not know how many blocks has this issue, I'd say at least 30. But I have not tool to verify no more blocks are affected.

### Expected output

Expected output is for the response to contain information about this transaction - https://origintrail.subscan.io/extrinsic/1471595-2, which is part of this block.

### Actual output

Running API call above i got this response, which tells me there was no errors and this block has no transactions. Which is different from subscan.io output, which lists one transaction for this block.

{"code":0,"message":"Success","generated_at":1682374187,"data":{"count":0,"list":null}}

**Comment by freehere107** [comment]
@botnumberseven Thanks for your feedback. This issue has been fixed.

**Comment by botnumberseven** [comment]
@freehere107 
Wow, that was fast, thank you.
Could you tell me what other blocks are affected by it?
I have a lot of transactions data in my hands now, but I have no idea what transactions I'm missing, because evm/transactions returned me nothing when I called the API.
List of affected blocks would be ideal, so I can avoid resyncing the whole chain.

**Comment by freehere107** [comment]
@botnumberseven maybe you can resync this blocks 
``1470021,1470099,1470134,1470295,1470333,1470365,1470384,1470392,1470505,1470527,1470558,1470757,1470827,1470869,1470918,1470926,1470953,1471005,1471037,1471139,1471218,1471366,1471478,1471533,1471595,1471633,1472047``
