### ISSUE TITLE
Polymesh returns second to last transfer instead of the latest

### ISSUE THREAD

**Issue by Noodles0x00** [subscan-explorer/subscan-issue-tracker#56]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

polymesh

### Steps to reproduce

try to call the api on a specific address with parameters 

row: 1
page: 1
address: (polyx address)

### Expected output

returns the very last transaction

### Actual output

returns the second last transaction

**Comment by Noodles0x00** [comment]
example code

def check_api(address):
    headers = {
        'Content-Type': 'application/json',
        'X-API-Key': 'api',
    }

    json_data = {
        'row': 1,
        'page': 1,
         'address': address,
    }

    response = requests.post('https://polymesh.api.subscan.io/api/v2/scan/transfers', headers=headers, json=json_data)

**Comment by freehere107** [comment]
@Noodles0x00 You should query using ``page= 0``

``
json_data = {
        'row': 1,
        'page': 1,
         'address': address,
    }`
``
