### ISSUE TITLE
Contract Verifying Error

### ISSUE THREAD

**Issue by ahmetzturk** [subscan-explorer/subscan-issue-tracker#59]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Astar Network

### Steps to reproduce

Astar Network
Google Chrome
https://astar.subscan.io/wasm_contract/bYLgJmSkWd4S4pTEacF2sNBWFeM4bNerS27FgNVcC9SqRE4?tab=contract
When attempting to verify the contract, it only accepts a single .rs file, but we have multiple .rs files. Consequently, we are unable to verify the smart contract on subscan. How can we resolve this issue?

### Expected output

Verified Contract

### Actual output

"This smart contract is verifying"

**Comment by freehere107** [comment]
hi, @ahmetzturk. Thanks for your feedback. We currently do not support multi-file verification. You can send me the contract code, I will support it after the next update.

**Comment by ahmetzturk** [comment]
https://github.com/ParasHQ/paras-ink-nft-launchpad-contract/tree/project/neurolauncher

**Comment by ahmetzturk** [comment]
Hello @freehere107
https://github.com/ParasHQ/paras-ink-nft-launchpad-contract/tree/project/neurolauncher

**Comment by ahmetzturk** [comment]
Hi,
https://github.com/ParasHQ/paras-ink-nft-launchpad-contract/tree/project/neurolauncher

BoBin ***@***.***>, 12 Haz 2023 Pzt, 12:06 tarihinde şunu
yazdı:

**Comment by LeoNeurolanche** [comment]
Hi I am Leo founder of Neurolanche and Astar Ambassador. We applied dApp staking on Astar Network. But We should definetly verify our contract to start our dApp staking. Can you check it please.

**Comment by freehere107** [comment]
hi, @ahmetzturk I try to build this contract has raised some error , please take a look

```
error: specialization impl does not specialize any associated items
--> paras-ink-nft-launchpad-contract/contracts/paras_launchpad/lib.rs:38:5
|
38 |     impl PSP34 for ParasLaunchpadContract {}
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: impl is a specialization of this impl
--> .cargo/git/checkouts/openbrush-contracts-4c291f7aab99c37d/107348d/contracts/src/token/psp34/psp34.rs:80:1
|
80 | impl<B, T> PSP34 for T
| ^^^^^^^^^^^^^^^^^^^^^^

error: specialization impl does not specialize any associated items
--> paras-ink-nft-launchpad-contract/contracts/paras_launchpad/lib.rs:39:5
|
39 |     impl PSP34Enumerable for ParasLaunchpadContract {}
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: impl is a specialization of this impl
--> .cargo/git/checkouts/openbrush-contracts-4c291f7aab99c37d/107348d/contracts/src/token/psp34/extensions/enumerable.rs:91:1
|
91 | impl<T> PSP34Enumerable for T
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: specialization impl does not specialize any associated items
--> paras-ink-nft-launchpad-contract/contracts/paras_launchpad/lib.rs:40:5
|
40 |     impl PSP34Metadata for ParasLaunchpadContract {}
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: impl is a specialization of this impl
--> .cargo/git/checkouts/openbrush-contracts-4c291f7aab99c37d/107348d/contracts/src/token/psp34/extensions/metadata.rs:64:1
|
64 | impl<T: Storage<Data>> PSP34Metadata for T {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: specialization impl does not specialize any associated items
--> paras-ink-nft-launchpad-contract/contracts/paras_launchpad/lib.rs:41:5
|
41 |     impl Ownable for ParasLaunchpadContract {}
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: impl is a specialization of this impl
--> .cargo/git/checkouts/openbrush-contracts-4c291f7aab99c37d/107348d/contracts/src/access/ownable/mod.rs:70:1
|
70 | impl<T: Storage<Data>> Ownable for T {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: specialization impl does not specialize any associated items
--> paras-ink-nft-launchpad-contract/contracts/paras_launchpad/lib.rs:157:5
|
157 |     impl Launchpad for ParasLaunchpadContract {}
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: impl is a specialization of this impl
--> paras-ink-nft-launchpad-contract/logics/impls/launchpad/launchpad.rs:69:1
|
69  | impl<T> Launchpad for T
| ^^^^^^^^^^^^^^^^^^^^^^^

error: specialization impl does not specialize any associated items
--> paras-ink-nft-launchpad-contract/contracts/paras_launchpad/lib.rs:158:5
|
158 |     impl Psp34Traits for ParasLaunchpadContract {}
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: impl is a specialization of this impl
--> paras-ink-nft-launchpad-contract/logics/impls/psp34_traits/psp34_traits.rs:33:1
|
33  | impl<T> Psp34Traits for T
| ^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `paras_launchpad` (lib) due to 6 previous errors
ERROR: `".rustup/toolchains/nightly-aarch64-apple-darwin/bin/cargo" "build" "--target=wasm32-unknown-unknown" "-Zbuild-std" "--no-default-features" "--release" "--target-dir=paras-ink-nft-launchpad-contract/target/ink/paras_launchpad" "--features" "ink/ink-debug"` failed with exit code: Some(101)

```

**Comment by emarai** [comment]
> hi, @ahmetzturk I try to build this contract has raised some error , please take a look

Hi @freehere107, make sure you cd into the `contracts/neurolauncher` first, after that, you can use cargo contract build. It looks like this,

```bash
$ cd contracts/neurolauncher
$ cargo +nightly contract build --release
```

**Comment by freehere107** [comment]
@emarai Hi, It Still has the same error, and my ide also prompts the same errors, which should be a code-level error.

**Comment by emarai** [comment]
@freehere107 Weird, it works fine on my end. I suspect it was because of version disparities. I've pushed the `Cargo.lock` file, to see if it makes any difference https://github.com/ParasHQ/paras-ink-nft-launchpad-contract/blob/project/neurolauncher/Cargo.lock. 

FYI I'm using the following versions for the build,

* cargo-contract: cargo-contract-contract 2.2.1-unknown-x86_64-unknown-linux-gnu
* toolchain: nightly-2023-03-13-x86_64-unknown-linux-gnu

**Comment by freehere107** [comment]
@emarai 
```
➜  paras-ink-nft-launchpad-contract git:(main) ✗ rustup toolchain list                                                    
stable-aarch64-apple-darwin
stable-x86_64-unknown-linux-gnu
nightly-2023-03-13-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin (override)
```

still failed.

**Comment by tomrowbo** [comment]
Facing a similar issue: https://github.com/subscan-explorer/subscan-issue-tracker/issues/71
