### ISSUE TITLE
Identity/Sub-identity not displayed!

### ISSUE THREAD

**Issue by alam807** [subscan-explorer/subscan-issue-tracker#60]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Kusama

### Steps to reproduce

Navigate to https://kusama.subscan.io/account/H1h4VJPKbk6XxhrxB3QGAonL7ZfGQeABucKHYykdZDxQSyw

The account's valid and verified identity/sub-identity is not resolved. It continues to display as "Unknown". 

### Expected output

The Account identity should display SafeStake.IO/02

Following is a correct identification at Statescan explorer:

![image](https://github.com/subscan-explorer/subscan-issue-tracker/assets/32053838/689f05e5-4072-4f3d-8e87-4150b8801113)

### Actual output

![image](https://github.com/subscan-explorer/subscan-issue-tracker/assets/32053838/74c6c9c1-ece1-4123-8e8b-341773b3ca02)

**Comment by freehere107** [comment]
Thank you for your feedback. The data has been recovered and we are still investigating.
