### ISSUE TITLE
Hello, please help me, I have suspended the transaction in the blockchain, my tokens have not entered my personal wallet 

### ISSUE THREAD

**Issue by Esi1374** [subscan-explorer/subscan-issue-tracker#62]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot

### Steps to reproduce

https://polkadot.subscan.io/extrinsic/0x9fadf3dc72703acbff52471372e31f52d5d0b76884584a03fdfc8132e1845652

### Expected output

12U2k2azUXJRbRZdanzzdXGx1rYb5JJHU1q1ab45TLDwpk9X

### Actual output

![Screenshot_۲۰۲۳۰۶۱۷_۲۱۳۵۳۰](https://github.com/subscan-explorer/subscan-issue-tracker/assets/100101740/486cf5a7-4181-4a84-bc01-755c0d78da82)

**Comment by freehere107** [comment]
@Esi1374 Can you add more details?
