### ISSUE TITLE
Duplicated transfers

### ISSUE THREAD

**Issue by brissenden** [subscan-explorer/subscan-issue-tracker#66]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot

### Steps to reproduce

1. Go to https://polkadot.subscan.io/extrinsic/14440684-2
2. Look at `Assets Transfer` section
3. There are two **identical** transfers with the same hash / amounts and other fields. Same thing is being returned in API.

### Expected output

I'd expect https://polkadot.subscan.io/extrinsic/14440684-2 to have just one transfer for `5.0011838592 DOT`.

### Actual output

Not sure :)

**Comment by brissenden** [comment]
Also I get balance differences when fetching all the transactions and comparing them with the balances returned by the API. The difference in balance is exactly the amount of the duplicated transaction.

**Comment by freehere107** [comment]
@brissenden This issue has been fixed. Thanks for your feedback

**Comment by brissenden** [comment]
Thanks!
