### ISSUE TITLE
Incorrect decimals / precision in a Moonbeam transaction

### ISSUE THREAD

**Issue by brissenden** [subscan-explorer/subscan-issue-tracker#67]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Moonbeam

### Steps to reproduce

1. Open EVM transaction https://moonbeam.subscan.io/tx/0x23622bc20a4d1a98ba206ee52b7fc19b434f48d2e7f2d05f1f544fbfd31d1be5 
2. Notice that `0.00000000009999` of `0006648936.c599` token is being transferred.
3. It looks like you use 18 decimals for this currency, below is the response from an API:

```
{"contract"=>"0x1dc78acda13a8bc4408b207c9e48cdbc096d95e0",
 "hash"=>"0x23622bc20a4d1a98ba206ee52b7fc19b434f48d2e7f2d05f1f544fbfd31d1be5",
 "create_at"=>1656023676,
 "from"=>"0x7ec7b375834ef33a1a677503d5065651ee530975",
 "to"=>"0x24a9d8f1f350d59cb0368d3d52a77db29c833d1d",
 "value"=>"99990000",
 "decimals"=>18,
 "symbol"=>"0006648936.c599",
 "name"=>"0006648936.c599",
 "from_display"=>{"address"=>"0x7ec7b375834ef33a1a677503d5065651ee530975"},
 "to_display"=>{"address"=>"0x24a9d8f1f350d59cb0368d3d52a77db29c833d1d", "evm_contract"=>{}}}
```

### Expected output

The same transaction in https://moonscan.io/tx/0x23622bc20a4d1a98ba206ee52b7fc19b434f48d2e7f2d05f1f544fbfd31d1be5 shows`0.9999 WBTC`.

### Actual output

I'd expect the API response to be equal:

```
{"contract"=>"0x1dc78acda13a8bc4408b207c9e48cdbc096d95e0",
 "hash"=>"0x23622bc20a4d1a98ba206ee52b7fc19b434f48d2e7f2d05f1f544fbfd31d1be5",
 "create_at"=>1656023676,
 "from"=>"0x7ec7b375834ef33a1a677503d5065651ee530975",
 "to"=>"0x24a9d8f1f350d59cb0368d3d52a77db29c833d1d",
 "value"=>"99990000",
 "decimals"=>8,
 "symbol"=>"0006648936.c599",
 "name"=>"0006648936.c599",
 "from_display"=>{"address"=>"0x7ec7b375834ef33a1a677503d5065651ee530975"},
 "to_display"=>{"address"=>"0x24a9d8f1f350d59cb0368d3d52a77db29c833d1d", "evm_contract"=>{}}}
```

### Additional factoids or references

* Similar issue happens to: https://moonscan.io/tx/0x831d7f8454d940e79a15c52f6a4a3ff6f5590437f6fd925090e32fc0069a8ddc vs https://moonbeam.subscan.io/tx/0x831d7f8454d940e79a15c52f6a4a3ff6f5590437f6fd925090e32fc0069a8ddc

**Comment by freehere107** [comment]
@brissenden This issue has been fixed. Thanks for your feedback

**Comment by brissenden** [comment]
Thank you @freehere107, it's working well now :)
