### ISSUE TITLE
Enormous fee in Kusama

### ISSUE THREAD

**Issue by brissenden** [subscan-explorer/subscan-issue-tracker#69]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Kusama

### Steps to reproduce

1. Go to https://kusama.subscan.io/extrinsic/0x93e65ba0724f7e7e4b4adc9a8a139bd10cb60ea0aabc054e2de5fd0e5cff707a
2. Look at `Estimated Fee` and/or `Used Fee`

### Expected output

* I would expect fee to be much lower.

### Actual output

The fee is enormous comparing to the amount transferred.

### Additional factoids or references

API response:
```
{"from"=>"CwfbH5VzMb5EFR5pkL9DpMnnH8cjjLKCFi3K6s3EDef7dyu",
 "to"=>"F3opxRbN5ZZRfqouvKtkA1JU9HcQVTorV9NUA9uJUpdasw9",
 "extrinsic_index"=>"7845092-3",
 "success"=>true,
 "hash"=>"0x93e65ba0724f7e7e4b4adc9a8a139bd10cb60ea0aabc054e2de5fd0e5cff707a",
 "block_num"=>7845092,
 "block_timestamp"=>1623277272,
 "module"=>"balances",
 "amount"=>"10",
 "amount_v2"=>"0",
 "usd_amount"=>"0",
 "fee"=>"181818734577451008",
 "nonce"=>28,
 "asset_symbol"=>"KSM",
 "asset_unique_id"=>"",
 "asset_type"=>"",
 "from_account_display"=>{"address"=>"CwfbH5VzMb5EFR5pkL9DpMnnH8cjjLKCFi3K6s3EDef7dyu"},
 "to_account_display"=>{"address"=>"F3opxRbN5ZZRfqouvKtkA1JU9HcQVTorV9NUA9uJUpdasw9", "display"=>"modlpy/cfund:2007"},
 "event_idx"=>0}
```

**Comment by freehere107** [comment]
@brissenden This issue has been fixed

**Comment by brissenden** [comment]
@freehere107 Thank you!
