### ISSUE TITLE
Some westend extrinsic pages always return `Internal Server Error` or `Bad Gateway`

### ISSUE THREAD

**Issue by btwiuse** [subscan-explorer/subscan-issue-tracker#73]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Westend

### Steps to reproduce

1. open https://westend.subscan.io/event?address=&module=electionprovidermultiphase&event=all&startDate=&endDate=&startBlock=&endBlock=&timeType=date&version=9430
2. click on any link to extrinsic ids, like https://westend.subscan.io/extrinsic/17690244-2
3. see `Internal Server Error` or `Bad Gateway`

### Expected output

the server should return a normal webpage

### Actual output

`Internal Server Error` or `Bad Gateway`

**Comment by WoeOm** [comment]
The extrinsic containing a large data was not parsed correctly. We have fixed this bug.
