### ISSUE TITLE
Rewards tab?

### ISSUE THREAD

**Issue by Ste-miner** [subscan-explorer/subscan-issue-tracker#75]
Hello boys and girls,

after your UI-change, I can't find the rewards tab anymore. Csn you please tell me how to check trading rewards from now?

Thank you, 

best regards, Ste.

**Comment by WoeOm** [comment]
What is the URL of the missing rewards tab page?

**Comment by Ste-miner** [comment]
It's on every Subscan page when I put my account adress in and have a look
at it all. Before your UI change there was a tab for rewards and you could
track your daily staking rewards. This tab now isn't there anymore.

Can you please tell me how to track the staking rewards from now. There are
many people saying the same. This tab is gone and we don't know how to
track the rewards.

Please have a look at the picture I send you. The rewards tab was in that
line where you can find "Extrinsics", "Vote", "Transfers" and so on.

Best regards, Ste.


WoeOm ***@***.***> schrieb am Mo., 23. Okt. 2023, 04:10:

**Comment by WoeOm** [comment]
We have updated the rewards data on the account page. Please try querying it again.

**Comment by Ste-miner** [comment]
Hello,

Now there is something like warning message with unlocked (...) and some
vote infos. Don't know what that means. Its not the normal stuff with
rewards shown up.

So I can't see the rewards. But the rewards tab is there. Only when you
click on it, no rewards visible.

WoeOm ***@***.***> schrieb am Mo., 23. Okt. 2023, 10:55:

**Comment by WoeOm** [comment]
To facilitate a quicker resolution of this issue, please provide the following information: 
1. the network you are querying (e.g., Polkadot, Kusama...)
2. the query's address
3. and it would be helpful if you could also include some screenshots

I didn't see the screenshots in the previous comments, It might have been lost during the submission. (Please have a look at the picture I send you. The rewards tab was in that
line where you can find "Extrinsics", "Vote", "Transfers" and so on.)

**Comment by Ste-miner** [comment]
Hello,

it's Subscan, Polkadex Mainnet.

Have a look at the screenshot.

Best regards,

WoeOm ***@***.***> schrieb am Mi., 25. Okt. 2023, 01:35:

**Comment by WoeOm** [comment]
Thanks for your reply to this issue. 
We found that in some cases, the rewards information cannot be displayed. We have fixed it. You may try to query the rewards again.

**Comment by Ste-miner** [comment]
Ok. Thank you. ✔🤝🏻

WoeOm ***@***.***> schrieb am Mi., 25. Okt. 2023, 09:39:
