### ISSUE TITLE
Download all Data button not working

### ISSUE THREAD

**Issue by Maker47** [subscan-explorer/subscan-issue-tracker#78]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot 

### Steps to reproduce

1. Polkadot 
2. Brave browser
3. Find Download all Data button below list of transactions

### Expected output

being able to download CSV file

### Actual output

Error message row must be 1 or greater

**Comment by freehere107** [comment]
@cuckooemm

**Comment by cuckooemm** [comment]
How to reproduce？ I download transaction data on the polkadot network and everything works fine

**Comment by Maker47** [comment]
Follow this guide to reproduce: https://support.polkadot.network/support/solutions/articles/65000172796-how-to-export-your-transaction-history-in-a-csv-file

**Comment by Maker47** [comment]
Extrinsic downloads no problem, transfers and rewards do not

**Comment by Maker47** [comment]
![Screenshot 2023-11-16 at 08 54 26](https://github.com/subscan-explorer/subscan-issue-tracker/assets/73118568/8e37e4ea-3ec0-44a6-846a-b3024a9de2c3)

**Comment by cuckooemm** [comment]
This issue has been fixed, thanks for the feedback

**Comment by Maker47** [comment]
Excellent, thanks
