### ISSUE TITLE
Page crashes when I expand transaction details on Vara Subscan

### ISSUE THREAD

**Issue by btwiuse** [subscan-explorer/subscan-issue-tracker#79]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Vara

### Steps to reproduce

1. open https://vara.subscan.io/event?&module=electionprovidermultiphase&event=all&startDate=&endDate=&startBlock=&endBlock=&timeType=block&version=9430
2. expand any [electionprovidermultiphase (SolutionStored)](https://vara.subscan.io/event?module=electionprovidermultiphase&event_id=SolutionStored) transaction by clicking the reverse triangle button
3. page crashes with `Application error: a client-side exception has occurred (see the browser console for more information).`

![image](https://github.com/subscan-explorer/subscan-issue-tracker/assets/54848194/21470cad-539f-48cb-9e90-96f4010bdf3a)

### Expected output

should display transaction details

### Actual output

Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by WoeOm** [comment]
The page did not catch the exception when handle null values. We've just fixed this issue, thanks for your feedback.

<img width="1311" alt="image" src="https://github.com/subscan-explorer/subscan-issue-tracker/assets/7368203/c02a5124-b157-402b-bc6a-0ec900a5499a">
