### ISSUE TITLE
Democracy locks for Polkadot are not accurate

### ISSUE THREAD

**Issue by muddlebee** [subscan-explorer/subscan-issue-tracker#82]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot

### Steps to reproduce

1. Go to 
2. Hover at Token Distribution -> Others

![image](https://github.com/subscan-explorer/subscan-issue-tracker/assets/8139783/1b558a98-4ef8-4b3e-ab8f-79446ed85c10)

### Expected output

It should show the OpenGov locks

### Actual output

showing 0 DOT

**Comment by carlhong** [comment]
<img width="519" alt="image" src="https://github.com/user-attachments/assets/f566f6f9-adbe-492b-a3b2-a7b531529470">
It is fixed now.
