### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by GregKingx** [subscan-explorer/subscan-issue-tracker#83]
### Network(s)

Aleph Zero

### Description

add the value of the transfer next to the number of tokens
<img width="1194" alt="Zrzut ekranu 2024-01-3 o 14 32 58" src="https://github.com/subscan-explorer/subscan-issue-tracker/assets/96143440/61a62ec8-dc8f-4c53-b2ac-ca7e407ec9b8">

### Use cases

important information that tells you what is the value at the moment of the transaction

**Comment by carlhong** [comment]
Thanks for your feedback, this is updated now.

**Comment by GregKingx** [comment]
pleasure was all mine :)
