### ISSUE TITLE
PARAMS ERROR

### ISSUE THREAD

**Issue by ivankaslovakia** [subscan-explorer/subscan-issue-tracker#84]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

SUBSPACE

### Steps to reproduce

![2024-01-05 15_05_30-Subscan _ Subspace Gemini 3G Account Detail_ st73svQMUQenpjPrN5sRaRqRo8sbdSm8Bak](https://github.com/subscan-explorer/subscan-issue-tracker/assets/85197207/40ef60f8-674d-45f0-8c47-bc8ba5b38951)

### Expected output

.

### Actual output

.

### Additional factoids or references

.

**Comment by freehere107** [comment]
@ivankaslovakia This issue has been fixed. Thanks for your feedback
