### ISSUE TITLE
Broken identity fields copy to clipboard

### ISSUE THREAD

**Issue by chevdor** [subscan-explorer/subscan-issue-tracker#85]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

All

### Steps to reproduce

Take an account with an idendity.
Copy web or twitter field (for instance).
Instead of getting ONLY the website (for instance) in the clipboard, you now get `Website:https://foo.bar/` which is highly not convenient :)

### Expected output

Just the field content, without its name.

### Actual output

name + field content

**Comment by WoeOm** [comment]
Thanks to your feedback, we have optimized the tooltip.

**Comment by chevdor** [comment]
Thank you @WoeOm, I confirm it now works again as it used to.
