### ISSUE TITLE
/api/scan/extrinsic event is null at this endpoint

### ISSUE THREAD

**Issue by puruoni** [subscan-explorer/subscan-issue-tracker#88]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot, Astar

### Steps to reproduce

1. Run this API
```
curl -X POST 'https://astar.api.subscan.io/api/scan/extrinsic' \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "extrinsic_index": "2860924-51"
  }'
```
2. Check the response. data.event is null.

### Expected output

data.event should not be null.

### Actual output

null

**Comment by freehere107** [comment]
@puruoni Thanks for your report. This issue has been fixed.
