### ISSUE TITLE
Pool account is shown as if it was mine

### ISSUE THREAD

**Issue by cocoxb** [subscan-explorer/subscan-issue-tracker#89]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot, Kusama

### Steps to reproduce

I’m the owner of the stakingpool #102 on Polkadot.
The reward account from the pool says „This account has asset or on-chain data in 1 other network.“
The address from the pool has no other network though.
The link does lead to the Kusama network, also stakingpool #102 on Kusama, what is a different one. Subscan shows this account as if it was mine but it is not related to my address so I don’t have the control over it of course.

Is this a known issue/bug?

### Expected output

Pool account #102 on Polkadot has no other network.

### Actual output

It shows pool account #102 on Kusama if it was mine.

**Comment by cuckooemm** [comment]
this is not a bug
The two accounts have the same public key, so they are one account
