### ISSUE TITLE
Missing validator entries in csv export file

### ISSUE THREAD

**Issue by Terminal-Geek** [subscan-explorer/subscan-issue-tracker#9]
### Network(s)

Kusama

### Description

Hi folks,

I really like your explorer, especially the export feature for transactions and rewards. What is missing in the export file though is the column with the validator addresses. It shows in the web frontend, but is not included in the csv. I’d need this for an analysis of my individual staking performance. Is there any chance to have this feature influded?

Regards
Toby

### Use cases

Analysis of individual staking performace via Excel

**Comment by MittWillson** [comment]
Hi, We will consider your feature request, and if any updates I will let you know

**Comment by MittWillson** [comment]
I wanna make sure one thing, Is that `Stash ` column is you needed? The `Stash` actually is `Validator Stash`

**Comment by Terminal-Geek** [comment]
> I wanna make sure one thing, Is that `Stash` column is you needed? The `Stash` actually is `Validator Stash`

Yes, that's it. Thank your for considering my feature request!
