### ISSUE TITLE
Staking rewards seem to be double in the extrinsic view

### ISSUE THREAD

**Issue by mutantcornholio** [subscan-explorer/subscan-issue-tracker#90]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Kusama

### Steps to reproduce

1. Go into account → rewards, like [here](https://kusama.subscan.io/reward?address=HP8qJ8P4u4W2QgsJ8jzVuSsjfFTT6orQomFD6eTRSGEbiTK&category=Reward&role=account&page=35), pick a reward, note the amount:
![Screen Shot 2024-02-13 at 12 16 07](https://github.com/subscan-explorer/subscan-issue-tracker/assets/588262/2ad55711-5272-45df-b6bb-d60cbcd31c8c)
2. Go inside the extrinsic, see "Total Reward" of double that amount: 
![Screen Shot 2024-02-13 at 12 16 13](https://github.com/subscan-explorer/subscan-issue-tracker/assets/588262/56a926e8-d9b0-47eb-a4ae-78cf5f719391)

### Expected output

I expect the amounts to match

### Actual output

They didn't match

**Comment by freehere107** [comment]
@mutantcornholio This issue has been fixed.
