### ISSUE TITLE
Wrong type description for some chains

### ISSUE THREAD

**Issue by btwiuse** [subscan-explorer/subscan-issue-tracker#91]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Enjin

### Steps to reproduce

Open https://www.subscan.io/account/efPjs1X2fo4ompPZsdBvyjE9xDEJasnbuTDMoMsjMJhPkZGRm and scroll down to the bottom 

### Expected output

Enjin Relay Chain address should have "Enjin Relay Chain" on the type column

### Actual output

Enjin Matrixchain

**Comment by carlhong** [comment]
Thanks for your feedback, it is updated.
