### ISSUE TITLE
Download List of Nominator Not Working

### ISSUE THREAD

**Issue by DaddyDillZero** [subscan-explorer/subscan-issue-tracker#92]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Aleph Zero

### Steps to reproduce

1. Switch to Aleph Zero network
2. Head to validator section
3. Click `View Other X Nominator`
4. Scroll down and click `Download Page Data`

### Expected output

Usually it downloads a .csv file with the appropriate list. 

### Actual output

It gives empty array.

**Comment by cuckooemm** [comment]
This issue has been fixed, thanks for the feedback

**Comment by DaddyDillZero** [comment]
Thanks guys.
