### ISSUE TITLE
Moonriver Indexing Issue - Duplicate accounts listed with different balances

### ISSUE THREAD

**Issue by x676f64** [subscan-explorer/subscan-issue-tracker#94]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Moonriver

### Steps to reproduce

See https://www.subscan.io/account/0xca345a15925C14e3DEb0AeDa5EBe5b772986Dcb4
The account page shows two Moonriver accounts with different balances
![image](https://github.com/subscan-explorer/subscan-issue-tracker/assets/53136615/333ff334-6107-4f85-968f-624484993e47)

### Expected output

One moonriver account

### Actual output

two moonriver accounts

**Comment by freehere107** [comment]
@x676f64 This issue has been fixed.
