### ISSUE TITLE
https://www.subscan.io/

### ISSUE THREAD

**Issue by bulo4ka8993** [subscan-explorer/subscan-issue-tracker#96]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Substrate

### Steps to reproduce

1. Substrate 
2. Chrome, Mozilla Firefox, Edge, Yandex browser, Brave. 

### Expected output

Hello. I am writing about the problem on the website https://www.subscan.io/. When I enter my address, I am redirected to the Subscan Polkadot website, although I should have stayed on the Subscan website with all my tokens. Plus, there is no search window on the Subscan website itself.
![1](https://github.com/subscan-explorer/subscan-issue-tracker/assets/123836560/eaee7ba2-87c0-4672-ad69-1e9de267b355)
I press the "find" button and it throws me here https://www.subscan.io/account/15hjAH9GXCLMkcSxeRcbdbtuQZ59pgL6rDU73FBknBprgNR8 (this is an example addres)
![2](https://github.com/subscan-explorer/subscan-issue-tracker/assets/123836560/e77f6ef2-9880-457b-bd33-3284c4a18d2e)
He writes that “Account not found on the Polkadot network” but just below it says that the address contains other assets.
![3](https://github.com/subscan-explorer/subscan-issue-tracker/assets/123836560/94402eda-6d34-413c-a03c-6494f60e667d)
By clicking on the "here" button I get to the site https://www.subscan.io/account/15hjAH9GXCLMkcSxeRcbdbtuQZ59pgL6rDU73FBknBprgNR8 As you can see, there is no search window for the address. I waited 2 days, but the problem did not go away. What's happening? And when will the problem be solved?

I emailed you with the same problem.: [hello@subscan.io](mailto:hello@subscan.io)

### Actual output

I would like to ask you what really happened

**Comment by cuckooemm** [comment]
this account does not exist on the polkdot network.
no balance and no operations

**Comment by bulo4ka8993** [comment]
This was an example address. Previously, the site left me in subschan, but I have to manually click on the “HERE” button and look at the rest of the tokens. I checked different addresses, same thing. The problem is not Polkadot, but the fact that the site is not working correctly. Why is there no search box on the Subscan website?

**Comment by carlhong** [comment]
Sorry for the inconvenience caused, we've updated it now.
