### ISSUE TITLE
Verify & Publish: Metadata file not found. Did you include \"metadata.json\"?

### ISSUE THREAD

**Issue by jtakalai** [subscan-explorer/subscan-issue-tracker#98]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Peaq (EVM)

### Steps to reproduce

1. Open https://peaq.subscan.io/account/0x3a9A81d576d83FF21f26f325066054540720fC34?tab=contract
2. select "Solidity (Standard-JSON-Input)
3. Compiler version 0.8.9
4. Upload https://gist.github.com/jtakalai/44012fd56bf5a29b5975778b25a745e2 as the file
5. Hit Verify & Publish

### Expected output

The contract verified

### Actual output

Toast saying "Request failed with status code 499", or "Metadata file not found. Did you include \"metadata.json\"?" (with status 500)

### Additional factoids or references

I've previously successfully validated a contract using the "Solidity (Single file)" option, but here it gave the same error. Also since this Standard-Input-JSON is direct from compiler to verified process with no manual tweaking (like flattening) in the middle, I decided to add it to the ticket.

**Comment by freehere107** [comment]
@jtakalai I have checked you uploaded JSON input file. This JSON is not a standard JSON input. You can refer to this document https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description
