### ISSUE TITLE
Rewards tab not showing data

### ISSUE THREAD

**Issue by gallak87** [subscan-explorer/subscan-issue-tracker#99]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot

### Steps to reproduce

Launch this page https://polkadot.subscan.io/account/15a9ScnYeVfQGL9HQtTn3nkUY1DTB8LzEX391yZvFRzJZ9V7?tab=reward

This is the validator Jaco/v4 - rewards page is showing no data but has a count.

### Expected output

Rewards data shows list of rewards

### Actual output

Rewards panel shows "No data"

**Comment by freehere107** [comment]
Hi, @gallak87 It looks good for now. Could you check it again?

**Comment by gallak87** [comment]
Yep looks fixed. Thx.
